blog/urls.py
from django.urls import path
from . import views
from django.urls import path, register_converter
from datetime import datetime


class DateConverter:
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value


register_converter(DateConverter, 'yyyy')


urlpatterns = [
    path('post-create/', views.PostCreate.as_view(), name='blog-post'),
    path('picture-story/', views.make_photo_story, name='picture-story'),
    path('add-picture-story/<int:pk>/', views.add_photo_to_story, name='add-picture-story'),
    path('delete-picture-story/<int:pk>/', views.delete_story, name='delete-picture-story'),

    path('picture-story-list/', views.LenSpeakListView.as_view(), name='picture-story-list'),
    path('picture-story-view/<int:pk>/<int:year>-<int:month>-<int:day>/<str:author>/<slug:tale>/',
         views.photo_story_view,
         name='picture-story-view'),
    path('picture-update/<int:pk>/', views.PhotoUpdateView.as_view(), name='picture-update'),
    path('picture-story-update/<int:pk>/<slug:tale>/<str:author>/', views.StoryUpdateView.as_view(),
         name='picture-story-update'),

    path('upload-images/<int:pk>/', views.add_photo_to_story, name='upload-images'),
    path('images-large/<int:pk>/', views.large_file, name='images-large'),
    path('images-large-direct/', views.large_file_direct, name='images-large-direct'),
    path('update-db/', views.update_db, name='update-db'),

    path('clear-images/<int:pk>/<int:story_pk>/', views.clear_database, name='clear-database'),

    path('post-draft/', views.post_draft, name='post-draft'),
    path('post-draft-detail/<int:pk>/', views.post_draft_detail, name='post-draft-detail'),
    path('post-draft-update/<int:pk>/', views.PostUpdate.as_view(), name='post-draft-update'),

    path('post-detail/<int:pk>/<int:year>-<int:month>-<int:day>/<slug:post>/<str:author>/',
         views.detail_view_show, name='post-detail-show'),
    path('post-detail/<int:pk>/', views.detail_view, name='post-detail'),

    path('post/<int:pk>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/', views.post_delete, name='post-delete'),
    path('post-delete/<int:pk>/', views.delete_post, name='delete-post'),
    path('comment/<int:pk>/<int:idx>/', views.comment_update, name='comment-update'),
    path('reply/<int:pk>/<int:idx>', views.reply_delete, name='reply-delete'),
    path('comment/<int:pk>/<int:idx>', views.comment_delete, name='comment-delete'),
    path('comment_reply/', views.reply_ajax, name='blog-comment-reply'),
    path('post-like/', views.post_like, name='post-like'),
    path('follow/', views.follow_users, name='follow'),
    path('twitter/', views.twitter_posts, name='blog-twitter'),
    path('twitter-search/', views.search_twitter, name='blog-twitter-search'),
    path('search/', views.search_view, name='blog-search'),
    path('about/', views.about, name='blog-about'),
    path('tnc/', views.tnc, name='blog-tnc'),
    path('privacy/', views.privacy, name='privacy'),
    path('author/<int:pk>/<str:author>', views.UserPostListView.as_view(), name='user-posts'),

    path('', views.PostListView.as_view(), name='blog-home'),

]

news/urls.py
from django.urls import path

from .views import (
                    news_search,
                    auto_search_news,

                    )

urlpatterns = [

    path('search-news/', news_search, name='search-news'),
    path('search-live/', auto_search_news, name='auto-search-news'),

]

wetoowrite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import blog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('member.urls')),
    path('', include('news.urls')),
    path('', include('article.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = blog.views.handler404
handler500 = blog.views.handler500

news/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

news/forms.py
from django import forms


class GetNews(forms.Form):
    search_term = forms.CharField(max_length=250, required=False,  widget=forms.TextInput(attrs={
        'style': 'display:inline-block;width:100%'}))
    country = forms.CharField(label="Select Country For News", required=False,
                              widget=forms.TextInput(
                                  attrs={'list': 'countries',
                                         'autocomplete': 'off',
                                         'style': 'display:inline-block'}))
    category = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'list': 'category',
               'autocomplete': 'off',
               'style': 'display:inline-block'}))

news/views.py
import logging

from django.shortcuts import render

import urllib.request
import requests
from .forms import GetNews
from django.http import JsonResponse


countries = (
    ('Argentina', 'ar'), ('Austria', 'at'), ('Australia', 'au'), ('Belgium', "be"), ('Bulgaria', 'bg'),
    ('Brazil', 'br'),
    ('Canada', 'ca'), ('China', 'cn'), ('Combodia', 'co'), ('Cuba', 'cu'), ('Czech', 'cz'), ('Germany', 'de'),
    ('Egypt', 'eg'), ('France', 'fr'), ('Britain', 'gb'), ('Greece', 'gr'), ('HongKong', 'hk'), ('Hungary', 'hu'),
    ('Indonesia', 'id'), ('Ireland', 'ie'), ('Israel', 'il'), ('India', 'in'), ('Italy', 'it'), ('Japan', 'jp'),
    ('Korea', 'kr'), ('New Zealand', 'nz'), ('Russia', 'ru'), ('Sweden', 'se'), ('Singapore', 'sg'), ('Thailand', 'th'),
    ('Turkey', 'tr'), ('Taiwan', 'tw'), ('USA', 'us'), ('South Africa', 'za'))

cat = (('business', 'business'), ('entertainment', 'entertainment'), ('general', 'general'), ('health', 'health'),
       ('science', 'science'), ('sports', 'sports'), ('technology', 'technology'))


def news_search(request):
    api_key = '03e6fb17fbfa4e809aca75b261067606'
    search_cat = ''
    search_country = ''
    news = ''
    if request.method == 'POST':
        form = GetNews(request.POST)
        if form.is_valid():
            search_news = form.cleaned_data['search_term']
            if form.cleaned_data['country']:
                country = form.cleaned_data['country']
                search_country = dict(countries)[country]
            if form.cleaned_data['category']:
                category = form.cleaned_data['category']
                search_cat = dict(cat)[category]
            url = ('https://newsapi.org/v2/top-headlines?q={}&country={}&category={}&language=en&apiKey={}'.format(
                search_news,
                search_country,
                search_cat,
                api_key))
            response = requests.get(url)
            news = response.json()
            context = {
                'form': form,
                'articles': news,
                'countries': list(countries),
                'cat': list(cat),
            }
            return render(request, 'news/search-news.html', context)
    else:
        form = GetNews()
        search_country = 'India'
        search_news = 'general'
        url = ('https://newsapi.org/v2/top-headlines?q={}&country={}&category={}&language=en&apiKey={}'.format(
            search_news,
            search_country,
            search_cat,
            api_key))
        response = requests.get(url)
        news = response.json()

    context = {
        'form': form,
        'articles': news,
        'countries': list(countries),
        'cat': list(cat),
    }
    return render(request, 'news/search-news.html', context)


def auto_search_news(request):
    api_key = '03e6fb17fbfa4e809aca75b261067606'
    form = GetNews(request.GET)
    if form.is_valid():

        search_data = form.cleaned_data.get('search_term')
        url = ('https://newsapi.org/v2/top-headlines?q={}&language=en&pageSize=10&apiKey={}'.format(search_data, api_key))
        response = requests.get(url)
        news = response.json()
        print('response', news.get('status'))
        logging.info(f'{news}')
        # to serialize non-dict object
        if news.get('status') == 'ok':
            return JsonResponse(news['articles'], safe=False)
        else:
            return JsonResponse({'error': 'no response'})
    return JsonResponse({'error': 'no response'})

news/templates/news/search-news.html
{%extends 'blog/base.html'%}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{%load static%}

{%block content%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <div class=" container " style="margin-top: 100px;">
            <h2 class="shadow p-3 mb-5 bg-white text-center rounded" >Get Latest News</h2><br>


    <div class="row">

        <form method="post" action="." id="news_form" >
        <div class="form-row align-items-center">

        <div class="col-lg-3 mb-sm-2">Fill any one or both field(s):</div>
                    {% csrf_token %}
                <div class="col-lg-3 mb-sm-3">
                    {{form.country|add_class:"form-control" }}
                </div>
                <div class="col-lg-3 mb-sm-3">
                    {{form.category|add_class:"form-control" }}
                </div>
                    <div class="col-lg-3 mb-sm-1">
                        <input type="submit" id="news_submit" data-form-data="news_form" class="btn btn-elegant">
                    <datalist id="countries">
                        {%for item in countries %}
                        <option value="{{item.0}}"></option>
                        {%endfor%}
                    </datalist>
                    <datalist id="category">
                        {%for item in cat %}
                        <option value="{{item.0}}"></option>
                        {%endfor%}
                    </datalist>
                </div>
        </div>
        </form>
        <div style="margin-top: 30px;">
            {%if articles.totalResults%}
            Total {{articles.totalResults}} Results retrieved!
            {%endif%}
            {%for article in articles.articles|slice:"10"%}
            <ul class="list-unstyled">
                <li class="media">
                    <img class="mr-3" width=250 height="150"
                         style="border:2px solid black;margin:2px;border-radius:7px;padding:5px"
                         src="{{article.urlToImage}}" onerror="this.src='https://i.imgur.com/2tRQjc5.png'"
                         alt="static/media/news/hawk.jpg">
                    <div class="media-body">
                        <a href="{{article.url}}" target="_blank"><span><strong>{{article.title}}</strong></span></a><br>
                        <span>{{article.publishedAt}}<strong> |</strong></span><span>By: {{article.author}}</span><br>
                        <span>{{article.content}}</span>
                    </div>
                </li>
            </ul>
            {%endfor%}
        </div>

        <form style="width:650px" method="post" action="." >
            <div style="margin-bottom: 20px;">
                <div class=" mx-auto mb-5">
                    <legend class="shadow p-3 mb-5 mt-5 bg-light rounded" style="color:blue;"><Strong> Search for news in Papers across the Globe!</Strong></legend>
                    {% csrf_token %}
                    {{form.search_term|add_class:"search"| add_class:"form-control"|attr:"placeholder:Search Here"|attr:"autocomplete:off"|attr:"width:100%"}}
                </div>
            </div>
        </form>
        <div class="mb-5"   style="margin-bottom: 20px;">
            <h4 class="result"></h4>
            <ul class="results">

            </ul>
        </div>
    </div>
</div>

{%endblock%}
{% block jquery %}
    <script>
    $(document).ready(function () {
        $('#id_country').val('India');
        $('#id_category').val('general');
    })
    </script>
    <script>
    var delayTimer;
$('.search').keyup(function() {
  clearTimeout(delayTimer);
  $('.results').text('Loading...');

  delayTimer = setTimeout(function() {
    var text = $('.search').val();
    console.log(text)
    $.ajax({
      url: '/search-live',
      data: {
        'search_term': text
      },
      dataType: 'json',
      success: function(data) {
        var result = '';
        $('.results').text('');
        data.forEach(function(item) {
            result +='<li><a target="_blank" href='+item["url"]+'>'+item['title']+'</a></li>'
            })
        $(".results").append(result);
        }
        }),1000});
        })

    </script>
    <script>

    </script>
{% endblock %}