blog/urls.py
from django.urls import path
from . import views
from django.urls import path, register_converter
from datetime import datetime


class DateConverter:
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value


register_converter(DateConverter, 'yyyy')


urlpatterns = [
    path('post-create/', views.PostCreate.as_view(), name='blog-post'),
    path('picture-story/', views.make_photo_story, name='picture-story'),
    path('add-picture-story/<int:pk>/', views.add_photo_to_story, name='add-picture-story'),
    path('delete-picture-story/<int:pk>/', views.delete_story, name='delete-picture-story'),

    path('picture-story-list/', views.LenSpeakListView.as_view(), name='picture-story-list'),
    path('picture-story-view/<int:pk>/<int:year>-<int:month>-<int:day>/<str:author>/<slug:tale>/',
         views.photo_story_view,
         name='picture-story-view'),
    path('picture-update/<int:pk>/', views.PhotoUpdateView.as_view(), name='picture-update'),
    path('picture-story-update/<int:pk>/<slug:tale>/<str:author>/', views.StoryUpdateView.as_view(),
         name='picture-story-update'),

    path('upload-images/<int:pk>/', views.add_photo_to_story, name='upload-images'),
    path('images-large/<int:pk>/', views.large_file, name='images-large'),
    path('images-large-direct/', views.large_file_direct, name='images-large-direct'),
    path('update-db/', views.update_db, name='update-db'),

    path('clear-images/<int:pk>/<int:story_pk>/', views.clear_database, name='clear-database'),

    path('post-draft/', views.post_draft, name='post-draft'),
    path('post-draft-detail/<int:pk>/', views.post_draft_detail, name='post-draft-detail'),
    path('post-draft-update/<int:pk>/', views.PostUpdate.as_view(), name='post-draft-update'),

    path('post-detail/<int:pk>/<int:year>-<int:month>-<int:day>/<slug:post>/<str:author>/',
         views.detail_view_show, name='post-detail-show'),
    path('post-detail/<int:pk>/', views.detail_view, name='post-detail'),

    path('post/<int:pk>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/', views.post_delete, name='post-delete'),
    path('post-delete/<int:pk>/', views.delete_post, name='delete-post'),
    path('comment/<int:pk>/<int:idx>/', views.comment_update, name='comment-update'),
    path('reply/<int:pk>/<int:idx>', views.reply_delete, name='reply-delete'),
    path('comment/<int:pk>/<int:idx>', views.comment_delete, name='comment-delete'),
    path('comment_reply/', views.reply_ajax, name='blog-comment-reply'),
    path('post-like/', views.post_like, name='post-like'),
    path('follow/', views.follow_users, name='follow'),
    path('twitter/', views.twitter_posts, name='blog-twitter'),
    path('twitter-search/', views.search_twitter, name='blog-twitter-search'),
    path('search/', views.search_view, name='blog-search'),
    path('about/', views.about, name='blog-about'),
    path('tnc/', views.tnc, name='blog-tnc'),
    path('privacy/', views.privacy, name='privacy'),
    path('author/<int:pk>/<str:author>', views.UserPostListView.as_view(), name='user-posts'),

    path('', views.PostListView.as_view(), name='blog-home'),

]

wetoowrite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import blog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('member.urls')),
    path('', include('news.urls')),
    path('', include('article.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = blog.views.handler404
handler500 = blog.views.handler500

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
import tweepy as tw
# for streaming activities
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
# get current user
from django_currentuser.middleware import (
    get_current_user, get_current_authenticated_user)
# As model field:
from django_currentuser.db.models import CurrentUserField
from taggit.managers import TaggableManager
from django.utils.text import slugify


# will post files to a dir named after the user
def upload_location(post, filename):
    return '%s/%s' % (post.author, filename)


def upload_location_for_comments(comments, filename):
    return '%s/%s' % (comments.post, filename)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_post')
    title = models.CharField(max_length=150)
    content = models.TextField()
    allow_comments = models.BooleanField('allow comments', default=True)
    slug = models.SlugField(max_length=150, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    cover = models.ImageField(blank=True, upload_to=upload_location, default='staticfiles/images/logo2.PNG')
    tags = TaggableManager()
    users_like = models.ManyToManyField(User, related_name="users_liked", blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)
    is_draft = models.BooleanField(default=True, blank=True)
    draft = models.BooleanField(default=True)
    key_point = models.BooleanField(verbose_name='Show key points', default=True)

    class Meta:
        ordering = ("-publish",)

    def __str__(self):
        return f'Post {self.title}, {self.author}'

    def get_absolute_url(self):
        return reverse('post-detail-show', args=[self.pk,
                                                 self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 slugify(self.author.get_full_name()),
                                                 slugify(self.title),
                                                 ])

    def get_full_name(self):
        return slugify(self.author.get_full_name())


class Comments(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_post_comment',
                             default=1)
    name = models.CharField(max_length=250)
    email = models.EmailField(max_length=150)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class CommentReply(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_post_comment_reply',
                             default=1)
    reply = models.CharField(max_length=1050)
    posted_on = models.DateTimeField(auto_now_add=True)
    comments = models.ForeignKey(Comments, on_delete=models.CASCADE, related_name='comments_reply')


class Contact(models.Model):
    user_from = models.ForeignKey("auth.User", related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey("auth.User", related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'


# add following fd to users dynamically
User.add_to_class('following', models
                  .ManyToManyField('self', through=Contact,
                                   # otherwise if one user follows another, reverser will
                                   # also be true
                                   related_name='followers', symmetrical=False))


# model to track user activity
class Action(models.Model):
    user = models.ForeignKey('auth.User', related_name='actions',
                             db_index=True, on_delete=models.CASCADE)
    verb = models.CharField(max_length=255)
    # used to record the target of user action
    target_ct = models.ForeignKey(ContentType, blank=True,
                                  null=True, on_delete=models.CASCADE)
    # limit_choices_to={'model': 'post'})...to limit drop down in admin...not being done now
    target_id = models.PositiveIntegerField(null=True, blank=True, db_index=True)
    # no record created in the db
    target = GenericForeignKey('target_ct', 'target_id')
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Action {self.verb} by {self.user} on {self.created}'


def pic_loc(instance, filename):
    posted_by = get_current_user()
    return '%s/%s' % (posted_by, filename)


class PhotoStory(models.Model):
    story_title = models.CharField(max_length=255, blank=True, default='Title of your Story', null=True)
    slug = models.SlugField(max_length=150, blank=True)
    story_content = models.TextField(blank=True, null=True, default='Write your Story', )
    uploaded_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photo_story')

    def __str__(self):
        return f'Photo {self.story_title} of {self.user}'

    def get_absolute_url(self):
        return reverse('picture-story-view', args=[self.pk,
                                                   self.uploaded_at.year,
                                                   self.uploaded_at.month,
                                                   self.uploaded_at.day,
                                                   slugify(self.user.get_full_name()),
                                                   self.slug,
                                                   ])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.story_title)
        return super(PhotoStory, self).save()

    def get_full_name(self):
        return slugify(self.user.get_full_name())

    class Meta:
        ordering = ['-uploaded_at']


class Photo(models.Model):
    photo_story = models.ForeignKey(PhotoStory, on_delete=models.CASCADE, related_name='story_photo', null=True)
    title_of_the_picture = models.CharField(max_length=255, blank=True, default='Title of the Pic/Video', null=True)
    describe_the_picture = models.CharField(max_length=255, blank=True, null=True, default='Describe the Pic/Video', )
    file = models.FileField(upload_to=pic_loc, blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return f'Photo {self.title_of_the_picture} of {self.photo_story} with {self.file}'

    def get_absolute_url(self):
        return reverse('picture-story-view', args=[self.photo_story.pk,
                                                   self.photo_story.uploaded_at.year,
                                                   self.photo_story.uploaded_at.month,
                                                   self.photo_story.uploaded_at.day,
                                                   slugify(self.photo_story.user.get_full_name()),
                                                   self.photo_story.slug,
                                                   ])

    class Meta:
        ordering = ['-uploaded_at', ]

blog/forms.py
from django import forms
from django.shortcuts import render
import tweepy as tw

from .models import Post, CommentReply, Comments, Contact, Photo, PhotoStory


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content', 'cover', 'tags', 'is_draft', 'key_point']


class CommentsForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Comments
        fields = ('name', 'email', 'body')

    def __init__(self, *args, **kwargs):
        initial_arguments = kwargs.get('initial', None)
        updated_initial = {}
        if initial_arguments:
            user = initial_arguments.get('name', None)#'name' comes from the initial in view.py def post_detai_view
            if user:
                updated_initial['name'] = getattr(user, 'first_name', None)
                updated_initial['email'] = getattr(user, 'email', None)
                updated_initial['body'] = 'Please provide a comment!'
                kwargs.update(initial=updated_initial)

        super(CommentsForm, self).__init__(*args, **kwargs)

        def com(request):
            if request.GET:
                form = CommentsForm(initial={'user': request.user, 'email': 'give your email'})
                return render(request, 'blog/post_detail.html', {'form': form})


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = CommentReply
        fields = ('name', 'reply')
        widgets = {
            'name': forms.TextInput(attrs={'required': False, 'autocomplete': False}),
            'reply': forms.TextInput(attrs={'required': False, 'autocomplete': False}),
        }


def get_trends():
    API_key = 'H6ybab13ZU5cdaUnj6KtP5AMI'
    API_secret = 'VXwYC9cmCnOqVzEpvWonVMqbUBtDX8KiUm40lpIzrz2IadNeeN'
    access_token = '1667776874-rBHAOHpytghmzJUEB7rs6gRi2cqWt3oja9jDF0k'
    access_token_secret = 'TyAztICP2ZU6nEUxgLuGDDmQLVV495YSDW97sRpCnPaYX'
    auth = tw.OAuthHandler(API_key, API_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = tw.API(auth, wait_on_rate_limit=True)
    trends1 = api.available_trends()
    complete_list = {}
    for i in range(len(trends1)):
        complete_list[trends1[i]['country']] = trends1[i]['woeid']
    selected = dict([(value, key) for key, value in complete_list.items()])
    a = list(selected.items())
    selected_tuple = ()
    for i in range(len(a)):
        selected_tuple = selected_tuple + (a[i],)
    return selected_tuple[1:]


selected = get_trends()


class TrendsForm(forms.Form):
    country = forms.CharField(label="Select a Country to see Trending Tweets",
                              widget=forms.TextInput(
                                  attrs={'onchange': 'this.form.submit()',
                                         'list': 'countries', 'class': 'form-control',
                                         'autocomplete': 'off', 'required': 'false'}))

    def clean(self):
        cleaned_data = super(TrendsForm, self).clean()
        try:
            trends = cleaned_data['country']
        except Exception:
            trends = 'India'
        if not trends:
            raise forms.ValidationError('You have to write something!')
        return trends


class TwitterSearchForm(forms.Form):
    search_twitter = forms.CharField(label='Search Tweets', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Type a trending word here...',
               'onchange': 'this.form.submit()', 'autocomplete': 'off', 'required': 'false'}))


class PhotoForm(forms.ModelForm):
    # file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Photo
        fields = ('title_of_the_picture', 'describe_the_picture', 'file')


class PhotoStoryForm(forms.ModelForm):
    class Meta:
        model = PhotoStory
        fields = ('story_title', 'story_content')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <link href="https://fonts.googleapis.com/css2?family=Rye&family=Vast+Shadow&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">

    <div class="view">
        <div class="white-text text-center mb-5" style="background-color: #1c2a48;; min-height: 15vh; margin-top: 100px;">
            <h1 style="font-family: 'Rye', cursive; font-size: 40px; letter-spacing: 4px;">About We Too Write</h1>

        </div>
    </div>
    <div class="container" style="font-family: 'Montserrat', sans-serif;">
        <div class="row">
            <div class="col-md-12">
                <div class="card white-text mb-5">
                    <div class="card-header warning-color-dark ">
                        <h3>Wading Through Life</h3>
                    </div>
                    <div class="card-body ">
                        <h4 class="card-title warning-color">Articles on Spreading Information and Wisdom</h4>
                        <section style="color: black; text-align: justify">
                            <h5 class="card-text">This Site intends to be a repository of articles, short essays which
                                contain
                                lessons from the journey of life. The readers of these articles may become wiser and
                                approach similar life
                                situations armed with the wisdom and information acquired from these articles. </h5>
                            <h5 class="card-text">One article may cover only one important subject and amply draw out
                                lessons </h5>
                            <h5 class="card-text">The articles may be published in a series and mentioned
                                accordingly</h5>
                        </section>
                    </div>
                </div>
                <div class="card white-text mb-5">
                    <div class="card-header default-color-dark ">
                        <h3>Encountering Challenges</h3>
                    </div>
                    <div class="card-body ">
                        <h4 class="card-title default-color">Articles on Guidance for facing common challenges</h4>
                        <section style="color: black; text-align: justify">
                            <h5 class="card-text text-black-50">The Site intends to be of help to all young men and
                                women who are stepping
                                out of their homes to confront various challenges of life such as choosing a field for
                                further education or choosing
                                a career in a particular field</h5>
                            <h5 class="card-text">This dilemma is faced by one and all but there is lack of informed and
                                reliable guidance.</h5>
                            <h5 class="card-text">The experience gained by us as we go through our own situations needs
                                to be collated and this Site
                                intends to do the same so that in times to come, reliable and trustworthy guidance and
                                be obtained from this repository</h5>
                        </section>
                    </div>
                </div>
                <div class="card white-text mb-5">
                    <div class="card-header primary-color-dark ">
                        <h3>Topical Issues</h3>
                    </div>
                    <div class="card-body ">
                        <h4 class="card-title primary-color">Articles Covering Current Topics</h4>
                        <section style="color: black; text-align: justify">
                            <h5 class="card-text text-black-50">
                                Current issues generate the most interest. While they are already covered in detail in various
                                publications, the Articles posted here must carry out independent, authentic and in-depth research
                            </h5>
                            <h5 class="card-text text-black-50">
                                It should not just be another publication on the topic of current issues. Your analysis must be unique
                                draw attention to newer aspects on the subject and draw lessons in the spirit of this website.
                            </h5>
                        </section>
                    </div>
                </div>

                <div class="card white-text mb-5">
                    <div class="card-header unique-color-dark ">
                        <h3>How to Post</h3>
                    </div>
                    <div class="card-body ">
                        <h4 class="card-title stylish-color">Submitting Articles</h4>
                        <section style="color: black; text-align: justify">
                            <h5 class="card-text text-black-50">Members who have registered with the Website are invited
                                to post their Articles </h5>
                            <h5 class="card-text">The members are required to agree to the <a href="{% url 'blog-tnc' %}">T&C</a> prior to
                                registration</h5>
                            <h5 class="card-text">The Article can be written using the Simple Mark Down Editor available
                                on the Post page. There is help available on the editor for the same. There are handy news and twitter links to delve deep into and research on current topics</h5>
                            <h5 class="card-text">The submitted Article will be vetted for abiding by the <a href="{% url 'blog-tnc' %}">T&C</a> of the Website.
                            Articles meeting the criteria, will be published within one working day. In case of any aberrations, the same will be informed
                            to the author for suitable corrections and resubmission</h5>
                            <h5 class="card-text">The authors can update or delete their articles at any time.</h5>
                            <h5 class="card-text">There is a commenting system for each publication. Please login and use the same to give your comments.</h5>

                        </section>
                    </div>
                </div>
                <div class="card testimonial-card">
        <!-- Content -->
        <div class="card-body">
            <!-- Name -->
            <h4 class="card-title">Write to Us</h4>
            <hr>
            <!-- Quotation -->
            <p><img src="https://img.icons8.com/clouds/100/000000/email.png"/>
                <a href="mailto:from.wetoowrite@gmail.com" target="_blank">We Too Write Team</a>
            </p>
           <a href="{% url 'privacy' %}">Privacy Policy</a>
           <a href="{% url 'blog-tnc' %}">Terms & Conditions</a>
        </div>
    </div>
            </div>

        </div>
    </div>
{% endblock content %}
{% block jquery %}
    <script>

    </script>
{% endblock jquery %}

blog/templates/blog/large_upload.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}
    <div class="container" style="margin-top: 100px; margin-bottom: 50px;">
        <div class="row">
            <div class="col-md-12 mt-5">

                'Uploading a large file'


                <progress id="progressBar" style="height: 10px; width: 100%" max=”100” value=”0”></progress>
                <p class="text-center teal-text" id="percentageCalc"></p>
                <form action="{% url 'images-large' story.id %}" id="upload" method="post" enctype="multipart/form-data"
                      style="padding: 5px;">
                    {% csrf_token %}

                    <h2 class="mt-2">Upload Large Media Files</h2> <br>
                    {{ form.title_of_the_picture.label_tag }}
                    {{ form.title_of_the_picture|add_class:"form-control" }}
                    {{ form.describe_the_picture.label_tag }}
                    {{ form.describe_the_picture|add_class:"form-control" }}
                    <input type="file" class="btn btn-success" id="id_file_upload">
                    <input type="text" hidden name="file" id="id_file" value="">

                </form>

            </div>
        </div>
    </div>
{% endblock %}
{% block jquery %}
    <script>
        let uploadedFile;


        let postData = new FormData();
        (function () {
            document.getElementById("id_file_upload").onchange = function () {
                var files = document.getElementById("id_file_upload").files;
                var file = files[0];
                if (!file) {
                    return alert("No file selected.");
                }
                getSignedRequest(file);
            };

        })();

        function getSignedRequest(file) {
            let xhr = new XMLHttpRequest();
            xhr.open("GET", "/images-large-direct?file_name=" + file.name + "&file_type=" + file.type);
            console.log(file.size);
            xhr.onreadystatechange = function () {

                if (xhr.readyState === 4) {
                    if (xhr.status === 200) {
                        let response = JSON.parse(xhr.responseText);
                        uploadFile(file, response.data, response.url);
                         $('#id_file_upload').hide();
                    } else {
                        alert("Could not get signed URL.");
                    }
                }
            };
            xhr.send();
        }

        {#function for progress bar#}

        function progressFunction(evt) {
            var progressBar = document.getElementById("progressBar");
            var percentageDiv = document.getElementById("percentageCalc");
            if (evt.lengthComputable) {
                progressBar.max = evt.total;
                progressBar.value = evt.loaded;
                var percentage = Math.round(evt.loaded / evt.total * 100) + "%";
                let fileSize = Math.round(evt.total / 1000000) + "Mb";
                percentageDiv.innerHTML = `File Size ${fileSize}...   Uploaded ${percentage}`;
            }
        }

        function uploadFile(file, s3Data, url) {
            var xhr = new XMLHttpRequest();
            xhr.upload.addEventListener("progress", progressFunction, false);
            xhr.open("POST", s3Data.url);

            xhr.setRequestHeader('x-amz-acl', 'public-read');
            for (key in s3Data.fields) {
                postData.append(key, s3Data.fields[key]);
            }
            postData.append('file', file);

            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4) {
                    console.log('xhr', xhr.status);
                    if (xhr.status === 200 || xhr.status === 204) {
                        {#document.getElementById("preview").src = url;#}
                        document.getElementById("id_file").value = "{{ user }}" + "/" + file.name;

                        uploadedFile = $('#id_file').val();
                        let title = $('#id_title_of_the_picture').val();
                        let description = $('#id_describe_the_picture').val();
                        let story_id = '{{ story_id }}';

                        $.post({% url 'update-db' %}, {
                            uploadedFile: uploadedFile, title: title,
                            description: description, story_id: story_id
                        }, function (data) {
                            location.reload()
                        })
                    } else {
                        alert("Could not upload file.");
                    }
                }
            };
            xhr.send(postData)
        }

    </script>
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.1.24.min.js"></script>
{% endblock jquery %}

blog/templates/blog/latest.html
<ul>
{% for post in latest_posts %}
<li>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</li>
{% endfor %}
</ul>
<!--for inclusion tag-->

blog/templates/blog/photo_update_form.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}

{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}
    <div class="container" style="margin-top: 100px; margin-bottom: 50px;">
        <div class="row">
            <div class="col-md-10 mt-5">
               {% file_ends_with object.file as video %}
                {% if not video %}
                <figure>
                    <a href="#" id="img"><img src="{{ object.file.url }}" height="200px" width="300px" alt=""></a>
                    <figcaption>
                        <p>Current Picture</p>
                    </figcaption>
                </figure>
                {% endif %}
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <legend>
                        {% if not video %}Update Picture{% elif video %} Update Video {% endif %}
                    </legend>
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-outline-indigo">
<small>If your file size is more than 1 Mb, delete this post. Click <a href="{% url 'images-large' object.photo_story.id %}">here</a> for uploading a video or image files larger than 1Mb
</small>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block jquery %}
    <script>
        $(document).ready(function () {
            $('#id_file').addClass('btn btn-primary');
            $('a#img').click(function (e) {
                e.preventDefault();
                $('#id_file').click()
            })
        })
    </script>
{% endblock jquery %}

blog/templates/blog/photostory_list.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mb-5" style="margin-top: 100px; ">
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <h4 class="bg-success white-text">{{ message }}</h4>
                {% endfor %}
            </div>
        {% endif %}
        <h2 style="background-color: #3e2723" class="text-center white-text"><strong>Picture Stories</strong></h2>
        {% for photo_story in object_list %}
            <img class="rounded-circle mb-2" src="{{ photo_story.story_photo.first.file.url }}" height="50px"
                 width="50px" alt="">
            <h4 class="d-inline ml-3">A Photo story <a
                    href="{{ photo_story.get_absolute_url }}">{{ photo_story.story_title }}</a>
                by {{ photo_story.user.get_full_name }} posted
                on {{ photo_story.updated_at|date:"d M" }}</h4><br><br>
        {% empty %}
            <h4> No stories yet </h4>
        {% endfor %}
        {% if user.is_authenticated %}
            <a href="{% url 'picture-story' %}" class="mx-auto">
                <button class="btn btn-outline-indigo mb-5 ">Add a Picture Story</button>
            </a>
        {% endif %}
    </div>
{% endblock %}